import { m } from "./characters/m";
import { n } from "./characters/n2";
import { o } from "./characters/o2";
import { i } from "./characters/i";
import { f } from "./characters/f";
import { d } from "./characters/d";
import { e } from "./characters/e";
import { b } from "./characters/b";
import { p } from "./characters/p";
import { l } from "./characters/l";
import { k } from "./characters/k";
import { r } from "./characters/r";
import { u } from "./characters/u";
import { t } from "./characters/t";
import { x } from "./characters/x";
import { z } from "./characters/z";
import { v } from "./characters/v";
import { c } from "./characters/c";
import { s } from "./characters/s";
import { g } from "./characters/g2";
import { a } from "./characters/a";
import { j } from "./characters/j";
import { y } from "./characters/y";
import { q } from "./characters/q2";
import { w } from "./characters/w";
import { h } from "./characters/h";
import { one } from "./characters/1";
import { two } from "./characters/2";
import { three } from "./characters/3";
import { four } from "./characters/4";
import { five } from "./characters/5";
import { six } from "./characters/6";
import { seven } from "./characters/7";
import { eight } from "./characters/8";
import { nine } from "./characters/9";
import { zero } from "./characters/0";
import { star } from "./characters/star";
import { percent } from "./characters/percent";
import { dollar } from "./characters/dollar";
import { at } from "./characters/at";
import { ques } from "./characters/ques";
import { slash } from "./characters/slash";
import { closeBracket } from "./characters/closeBracket";
import { openBracket } from "./characters/openBracket";
import { openBrace } from "./characters/openBrace";
import { closeBrace } from "./characters/closeBrace";
import { period } from "./characters/period";
import { openParen } from "./characters/openParen";
import { closeParen } from "./characters/closeParen";
import { plus } from "./characters/plus";
import { dash } from "./characters/dash";
import { underscore } from "./characters/underscore";
import { ampersand } from "./characters/ampersand";
import { equals } from "./characters/equals";
import { hash } from "./characters/hash";
import { tilde } from "./characters/tilde";
import { backslash } from "./characters/backslash";
import { pipe } from "./characters/pipe";
import { exclaim } from "./characters/exclaim";
import { carat } from "./characters/carat";
import { colon } from "./characters/colon";
import { comma } from "./characters/comma";
import { semicolon } from "./characters/semicolon";
import { greaterthan } from "./characters/greaterthan";
import { lessthan } from "./characters/lessthan";
import { singlequote } from "./characters/singlequote";
import { doublequote } from "./characters/doublequote";
import { backtick } from "./characters/backtick";

export default function char(
  string,
  svg,
  xpos,
  ypos,
  xoff,
  yoff,
  fontsize,
  weight,
  wig,
  id,
  update,
  cons,
  color,
  absolute_offset
) {
  switch (string) {
    case "a":
      a(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "b":
      b(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "c":
      c(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "d":
      d(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "e":
      e(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "f":
      f(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "g":
      g(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "h":
      h(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "i":
      i(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "j":
      j(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "k":
      k(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "l":
      l(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "m":
      m(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "n":
      n(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "o":
      o(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "p":
      p(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "q":
      q(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "r":
      r(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "s":
      s(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "t":
      t(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "u":
      u(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "v":
      v(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "w":
      w(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "x":
      x(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "y":
      y(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "z":
      z(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "A":
      a(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "B":
      b(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "C":
      c(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "D":
      d(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "E":
      e(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "F":
      f(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "G":
      g(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "H":
      h(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "I":
      i(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "J":
      j(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "K":
      k(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "L":
      l(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "M":
      m(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "N":
      n(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "O":
      o(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "P":
      p(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "Q":
      q(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "R":
      r(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "S":
      s(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "T":
      t(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "U":
      u(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "V":
      v(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "W":
      w(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "X":
      x(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "Y":
      y(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "Z":
      z(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "1":
      one(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "2":
      two(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "3":
      three(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "4":
      four(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "5":
      five(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "6":
      six(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "7":
      seven(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "8":
      eight(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "9":
      nine(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "0":
      zero(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
      break;
    case "*":
      star(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "%":
      percent(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "$":
      dollar(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "@":
      at(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "?":
      ques(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "/":
      slash(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "}":
      closeBracket(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "{":
      openBracket(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "[":
      openBrace(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "]":
      closeBrace(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case ".":
      period(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "(":
      openParen(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case ")":
      closeParen(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "+":
      plus(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "-":
      dash(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "_":
      underscore(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "&":
      ampersand(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "=":
      equals(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "#":
      hash(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "~":
      tilde(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "\\":
      backslash(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "|":
      pipe(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "!":
      exclaim(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "^":
      carat(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case ":":
      colon(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case ",":
      comma(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case ";":
      semicolon(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case ">":
      greaterthan(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "<":
      lessthan(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "'":
      singlequote(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case '"':
      doublequote(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
    case "`":
      backtick(
        svg,
        xpos,
        ypos,
        xoff,
        yoff,
        fontsize,
        weight,
        wig,
        id,
        update,
        cons,
        color,
        absolute_offset
      );
      break;
  }
}
